name: Lazor_Project_Group10 -- Welcome to the CPW Lazor App Solver
markdown: redcarpet
pygments: true
gituser: waynemonteiro97
paginate: 5
paginate_path: "page:num"
email: wmontei1@jhu.edu
#disqus: bitwiser
ga_id: UA-47902363-1
ga_domain: bitwiser.in
desc: Lazor project.
keywords: bitwiser, jekyll, theme, templates
#twitter: brijeshb42

theme: jekyll-theme-modernist